title: "Learn Kotlin/Native"
tagline: "A gentle introduction to Kotlin/Native."
url: https://tslamic.github.io
baseurl: /learn-kotlin-native
desc: The best resource on the web to learn Kotlin/Native.

author:
  name: "Tadej"
  url: http://www.tadej.me
  twitter: https://twitter.com/tadejslamic
  email: learnkotlinnative@gmail.com

markdown: kramdown
highlighter: rouge
plugins: [ jekyll-paginate, jekyll-gist, jekyll-sitemap ]
permalink: pretty
github:
  repo: https://github.com/tslamic/learn-kotlin-native
copyright: 'All content on this website is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>. Built with Jekyll using the <a href="http://hyde.getpoole.com/" target="_blank">Hyde</a> theme. The Kotlin logo is the property of <a href="https://www.jetbrains.com" target="_blank">JetBrains</a>. Made with ❤️ by <a href="http://www.tadej.me" target="_blank">Tadej</a>'
